### ISSUE TITLE
Man in the Middle Attacks

### ISSUE THREAD

**Issue by selected-pixel-jameson** [r0ml/OpenCV#3]
When I attempted to install this I received an error stating that it was unable to download sub-modules and then received warnings stating that a man in the middle attack was occurring and that I might being watched. 

Hoping that this isn't the actual case. 

I was not trying to build my own version or anything like that. I just installed the package via SPM and then updated the build process according to the docs.

**Comment by r0ml** [comment]
This repository contains all the requirements to rebuild a binary framework -- including the submodules which contain the OpenCV and contrib sources.  When I created it, I thought that SPM would not check out the submodules -- but it does.  These may take some time to download.  People have had trouble with the submodule checkouts timing out on slower or flakier internet connections -- but you are the first to report the man-in-the-middle attack warning.   

I have created a separate package:  https://github.com/r0ml/JustTheBinary  which just contains the binary xcframework without all the supporting resources to recreate the binary.  You may find that this downloads faster and (since it does not have submodules) should not trigger the warning you saw.  Try it and let me know if that works for you.
